ALTER TABLE omix_orders ADD COLUMN IF NOT EXISTS area TEXT;
ALTER TABLE omix_orders ADD COLUMN IF NOT EXISTS landmark TEXT;
ALTER TABLE omix_orders ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE omix_orders ADD COLUMN IF NOT EXISTS loyalty_points_used INTEGER DEFAULT 0;
ALTER TABLE omix_orders ADD COLUMN IF NOT EXISTS referral_code TEXT;
ALTER TABLE omix_orders ADD COLUMN IF NOT EXISTS order_items JSONB;
