services:
  - type: static
    name: stor1
    repo: https://github.com/oliver4441/stor1
    branch: main
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
